# .sops.yaml

keys:
  - &alisher "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKLB7lnUc9iy4UYdAl5q2qmrB1VEuRMcucluAe6WFpYV a.khssnv@gmail.com"
  - &2-vpsza500 age1mfv5z72hm57qqkn8lwgh4mqkgzvh48zpuxtz5p248h7yqzx8443s9avspv
creation_rules:
  - path_regex: ^secrets\.yaml$
    key_groups:
      - age:
        - *alisher
        - *2-vpsza500
