all:
  hosts:
    1.contabo:
      ansible_host: 1.contabo.khassanov.xyz
      wireguard_address: 10.9.0.1/32
      wireguard_allowed_ips: 10.9.0.1/32
      wireguard_endpoint: 1.contabo.khassanov.xyz
    rockpix:
      ansible_host: 192.168.88.5
      wireguard_address: 10.9.0.2/32
      wireguard_allowed_ips: 10.9.0.2/32
      wireguard_endpoint: ""
  children:
    k3s:
      hosts:
        1.contabo:
        rockpix:
    wireguard:
      hosts:
        1.contabo:
        rockpix:
